# Generated by Django 5.0.2 on 2024-05-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskology', '0005_taskcategory_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
